language: node_js

node_js:
    - "4"
    - "6"
    - "8"
    - "10"
    - "12"
    
matrix:
    allow_failures:
        - node_js: "4"
        - node_js: "6"
        - node_js: "8"

before_install:
    # execute all of the commands which need to be executed 
    # before installing dependencies

install:
    # install all of the dependencies we need here
    - npm install

before_script:
    # execute all of the commands which need to be executed 
    # before running actual tests
    - git submodule update --remote --recursive

script:
    # execute all of the tests or other commands to determine
    # whether the build will pass or fail
    - mocha

after_script: